twig:
    file_name_pattern: "*.twig"
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["base_form.html.twig"]
    date:
        timezone: "Europe/Paris"

when@test:
    twig:
        strict_variables: true
